ap:
  build: '../docker'
  container_name: procan-backend
  links:
    - mongo:mongo
    - redis:redis
  ports:
    - '3000:3000'
  volumes:
    - '../build:/app'
  environment:
    - smtphost=smtp.gmail.com
    - smtpport=465
    - smtpaccount= # smtp account
    - smtppass= # smtp password

mongo:
  image: mongo:3.6.8-stretch
  volumes:
    - '~/procan/mongo-data:/data/db'
  ports:
    - '27017:27017'
  command: mongod --smallfiles

redis:
  image: redis:4.0.11-stretch
  volumes:
    - '~/procan/redis-data:/data/kvs'